### ISSUE TITLE
png++ No such file or directory

### ISSUE THREAD

**Issue by razaina** [GReaperEx/Brainfunk#2]
Hi,

Any idea regarding this compilation error?

![fail](https://cloud.githubusercontent.com/assets/360746/23611431/98b577f0-0277-11e7-99ba-fe360727cca8.gif)

cheers

**Comment by razaina** [comment]
Nevermind, just had to install C++ wrapper for libpng

**Comment by GReaperEx** [comment]
Yes, you need png++ for variants that manipulate images, such as Brainloller.
