### ISSUE TITLE
Release number

### ISSUE THREAD

**Issue by misuchiru03** [GReaperEx/Brainfunk#4]
Would it be possible to add a release number to this?

**Comment by GReaperEx** [comment]
It has a version string, currently "0.9.0". Is that what you mean?

**Comment by misuchiru03** [comment]
Not exactly. That's good, but I am referring to [this page](https://github.com/GReaperEx/Brainfunk/releases)

**Comment by GReaperEx** [comment]
Oh, I see. Haven't thought of tagging it, but I guess I should.

**Comment by misuchiru03** [comment]
Sure thing.  It's not a huge issue, but if it were to be packaged up for a distro, sometimes version tags are required.  It also helps keep track better, lets someone get an older version with a tarball if they want to.
